### ISSUE TITLE
CI/CD: sign using Jetbrains marketplace signer instead

### ISSUE THREAD

**Issue by AgiMaulana-Justika** [AgiMaulana/FlutterTestFileCreatorIntellijPlugin#12]
Gradle signer causes
```
java.lang.NullPointerException: pemObject must not be null
```
https://github.com/AgiMaulana/FlutterTestFileCreatorIntellijPlugin/runs/6948621993?check_suite_focus=true

The current release signed with [JetBrains/marketplace-zip-signer](https://github.com/JetBrains/marketplace-zip-signer/releases) on local machine manually. Would be nice if we move this to Github Action.

Ref:
https://plugins.jetbrains.com/docs/intellij/plugin-signing.html#cli-tool

**Comment by AgiMaulana** [comment]
resolved in #16
